require 'rake'
require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/just_the_facts/Scraper'
require_relative '../lib/just_the_facts/Facts'
require_relative '../lib/just_the_facts/CLI'
require_relative '../lib/just_the_facts/version'
